# Generated by Django 4.0.3 on 2022-05-01 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('artist', models.CharField(default='', max_length=100)),
                ('album', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('audio', models.FileField(default='', upload_to='media/audio')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.edition')),
                ('year', models.ForeignKey(default=1994, on_delete=django.db.models.deletion.CASCADE, to='editions.year')),
            ],
            options={
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
