# Generated by Django 4.0.3 on 2022-12-29 00:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import songs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('artist', models.CharField(default='', max_length=100)),
                ('album', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('audio', models.FileField(storage=songs.models.OverwriteStorage(), upload_to='audio')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('thumbnail', models.ImageField(default='/song_thumbnails/music_icon.png', upload_to='')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.edition')),
                ('favourites', models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=256)),
                ('songs', models.ManyToManyField(related_name='songs', to='songs.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Playlists',
            },
        ),
    ]
