# Generated by Django 4.0.3 on 2022-12-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
