# Generated by Django 4.0.3 on 2022-04-30 23:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1994)])),
                ('short_year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Years',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.CharField(max_length=30)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('publisher', models.CharField(max_length=254)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('year', models.ForeignKey(default=1994, on_delete=django.db.models.deletion.CASCADE, to='editions.year')),
            ],
        ),
    ]
